theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
auto-format = true
bufferline = "always"
rulers = [80]
shell = ["zsh", "-c"]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":w!"
C-q = ":q!"
# C-S = "save_selection"
# C-n = ["move_line_down", "scroll_down"]
# C-p = ["move_line_up", "scroll_up"]
esc = ["collapse_selection", "keep_primary_selection"]